"""
Edit this file to define your group's chat ID and the birthdays you want loaded.

HOW TO GET GROUP_CHAT_ID:
  1. Add the bot to your Telegram group as normal.
  2. In the group, send: /chatid
  3. The bot replies with the chat's numeric ID (often negative for groups, e.g. -1001234567890).
  4. Paste that number below.

Then edit BIRTHDAYS below and run:  python seed_db.py
Re-run any time you add/change entries here — it's safe to run repeatedly
(it updates existing entries by name rather than duplicating them).
"""

GROUP_CHAT_ID = -5278097852  # <-- replace with your group's real chat ID

# language for this chat's birthday messages: "en" or "ru"
LANGUAGE = "en"

# username is optional — leave it as None (no quotes) if you don't have/want it
BIRTHDAYS = [
    # {"name": "Alice",   "day": 25, "month": 12, "year": 1990, "username": "alice_tg"},
    {"name": "Praveen Kumar", "day": 5, "month": 8, "year": 1980, "username": "ProfPraveen_India"},
    {"name": "Beibut Amirgaliyev", "day": 27, "month": 11, "year": 1986, "username": "beibuta"},
    {"name": "Tamara Zhukabayeva", "day": 11, "month": 8, "year": 1982, "username": "Zkkkkkt"},
    {"name": "Andrii Biloshchytskyi", "day": 23, "month": 9, "year": 1978, "username": None},
    {"name": "Didar Yedilkhan", "day": 30, "month": 5, "year": 1990, "username": "Didar5"},
    {"name": "Dinara Kaibasova", "day": 8, "month": 9, "year": 1978, "username": None},
    {"name": "Makpal Zhartybayeva", "day": 2, "month": 9, "year": 1988, "username": "makanaika"},
    {"name": "Lira La", "day": 29, "month": 6, "year": 1962, "username": None},
    {"name": "Ainur Zhumadillayeva", "day": 22, "month": 12, "year": 1982, "username": "Moonlight8217"},
    {"name": "Aigul Adamova", "day": 13, "month": 3, "year": 1984, "username": "AigulDyusenbinovna"},
    {"name": "Bolatzhan Kumalakov", "day": 6, "month": 2, "year": 1987, "username": "BolatzhanK"},
    {"name": "Gulzhan Soltan", "day": 6, "month": 11, "year": 1970, "username": None},
    {"name": "Zhanna Sadirmekova", "day": 4, "month": 6, "year": 1988, "username": None},
    {"name": "Aliya Nugumanova", "day": 17, "month": 12, "year": 1973, "username": None},
    {"name": "Madina Yermaganbetova", "day": 12, "month": 3, "year": 1977, "username": "Madinayermag"},
    {"name": "Shynar Akhmetzhanova", "day": 12, "month": 7, "year": 1970, "username": "Shynar1207"},
    {"name": "Grazioso Fabio", "day": 2, "month": 5, "year": 1969, "username": "fabiograzioso"},
    {"name": "Azamat Serek", "day": 12, "month": 2, "year": 1997, "username": "azasrh"},
    {"name": "Akerke Akanova", "day": 1, "month": 1, "year": 1972, "username": "Akerke_Akanova"},
    {"name": "Saltanat Sharipova", "day": 20, "month": 2, "year": 1991, "username": "saltonik"},
    {"name": "Aivar Sakhipov", "day": 22, "month": 4, "year": 1993, "username": "sahipov"},
    {"name": "Talgat Sembayev", "day": 30, "month": 6, "year": 1991, "username": None},
    {"name": "Symbat Nurgaliyeva", "day": 16, "month": 5, "year": 1989, "username": "Symbat2030"},
    {"name": "Aigerim Bakiyeva", "day": 1, "month": 7, "year": 1989, "username": "aigerimbakiyeva"},
    {"name": "Zhuldyz Basheyeva", "day": 12, "month": 5, "year": 1990, "username": None},
    {"name": "Shyryn Tutkyshbayeva", "day": 8, "month": 9, "year": 1986, "username": "shyryn_sarybai"},
    {"name": "Chingis Kharmyssov", "day": 16, "month": 11, "year": 1988, "username": "Chingis1988"},
    {"name": "Tolegen Akhmetov", "day": 28, "month": 7, "year": 1990, "username": "Tolegen_Akhmetov"},
    {"name": "Abzal Kyzyrkanov", "day": 28, "month": 8, "year": 1992, "username": "Abzzall"},
    {"name": "Alua Myrzakerimova", "day": 29, "month": 8, "year": 1992, "username": "alua_myrz"},
    {"name": "Nurzhamal Kashkimbayeva", "day": 25, "month": 9, "year": 1979, "username": None},
    {"name": "Gulnaz Zunimova", "day": 9, "month": 6, "year": 1990, "username": None},
    {"name": "Altynbek Seitenov", "day": 27, "month": 2, "year": 1992, "username": "albk27"},
    {"name": "Aigerim Kydyrbekova", "day": 26, "month": 11, "year": 1988, "username": "kydyrbekova_aigerim"},
    # {"name": "Aliya Katyetova", "day": None, "month": None, "year": None, "username": "Aliya254"},
    # {"name": "Marzhan Turarova", "day": None, "month": None, "year": None, "username": "Marzhan_123"},
    {"name": "Aigerim Aibatbek", "day": 8, "month": 6, "year": 1995, "username": "madame_aigerim"},
    {"name": "Elvira Aitmukhanbetova", "day": 3, "month": 8, "year": 1990, "username": "girlfromca"},
    {"name": "Shynggys Alshynov", "day": 19, "month": 1, "year": 1992, "username": "ShynAlshyn"},
    {"name": "Arailym Orazova", "day": 23, "month": 7, "year": 1992, "username": "aora2307"},
    {"name": "Dariya Bissengaliyeva", "day": 16, "month": 6, "year": 1997, "username": "missdariya"},
    {"name": "Dana Yespenbetova", "day": 13, "month": 10, "year": 1991, "username": "altynbekdana"},
    {"name": "Madina Kutubayeva", "day": 12, "month": 2, "year": 1996, "username": "mmdnn1"},
    {"name": "Zarina Kutpanova", "day": 5, "month": 4, "year": 1989, "username": None},
    {"name": "Kuralay Makhmetova", "day": 1, "month": 8, "year": 2000, "username": "niholuv"},
    {"name": "Ruslan Omirgaliyev", "day": 30, "month": 6, "year": 1997, "username": "romirgaliyev"},
    {"name": "Zhibek Sarsenova", "day": 26, "month": 12, "year": 1991, "username": "zhoogle"},
    {"name": "Algys Saltanat", "day": 10, "month": 1, "year": 1988, "username": None},
    {"name": "Zhaksylyk Kozhakhmet", "day": 18, "month": 6, "year": 1996, "username": "kzfromkz"},
    {"name": "Askar Khaimuldin", "day": 14, "month": 1, "year": 1993, "username": "akhaimuldin"},
    {"name": "Nursultan Khaimuldin", "day": 29, "month": 4, "year": 1991, "username": "mrkhaimuldin"},
    {"name": "Botagoz Mirzagalikova", "day": 29, "month": 4, "year": 1990, "username": "alonsaquixana"},
    {"name": "Bakyt Bakayeva", "day": 23, "month": 5, "year": 1992, "username": "bakytbb"},
    {"name": "Yersultan Tulebayev", "day": 15, "month": 1, "year": 1991, "username": "yyyy12345000"},
    {"name": "Konstantin Latuta", "day": 11, "month": 1, "year": 1984, "username": "konsteacher"},
    {"name": "Daniyar Baizhaksynov", "day": 29, "month": 4, "year": 1994, "username": "don_daniyar"},
    {"name": "Gulnur Shuteyeva", "day": 4, "month": 5, "year": 1986, "username": "shuteyeva0405"},
    {"name": "Nurtas Nadirov", "day": 27, "month": 7, "year": 1999, "username": "mrndir"},
    {"name": "Dinara Zhunissova", "day": 4, "month": 7, "year": 1989, "username": "dinaratursun"},
    {"name": "Nurgul Aziyeva", "day": 21, "month": 9, "year": 1982, "username": None},
    {"name": "Islam Omirzak", "day": 28, "month": 1, "year": 1994, "username": "iodce"},
    {"name": "Kamila Tanyrbergenova", "day": 28, "month": 1, "year": 1991, "username": "kamilatanyr"},
    {"name": "Aldiyar Salkenov", "day": 12, "month": 10, "year": 1995, "username": "salkenov1"},
    {"name": "Alibek Orynbek", "day": 21, "month": 7, "year": 1991, "username": "aleke91"},
    {"name": "Sandibek Umirov", "day": 27, "month": 4, "year": 1990, "username": "sandibekumirov"},
    {"name": "Almas Myrzakhmetov", "day": 12, "month": 8, "year": 1991, "username": "Almas09900"},
    {"name": "Altynbek Toleu", "day": 1, "month": 2, "year": 1987, "username": "toleu_altynbek"},
    {"name": "Aliya Aubakirova", "day": 8, "month": 10, "year": 1996, "username": "Ray8177"},
    {"name": "Tomiris Zhaksylyk", "day": 3, "month": 7, "year": 2001, "username": "tomzhh"},
    {"name": "Gulsipat Abisheva", "day": 21, "month": 4, "year": 1995, "username": "Gulsipat"},
    {"name": "Nurbolat Amilbek", "day": 13, "month": 11, "year": 2002, "username": "He111senberggg"},
    {"name": "Almas Ospanov", "day": 21, "month": 10, "year": 1983, "username": "almos131"},
    {"name": "Arstan Makatov", "day": 3, "month": 5, "year": 1992, "username": "ars_m"},
    {"name": "Assel Alimzhan", "day": 7, "month": 12, "year": 2001, "username": "AsselTG"},
    {"name": "Aruzhan Ali", "day": 27, "month": 8, "year": 2002, "username": "goods0ul"},
    {"name": "Kenzhegali Nurgaliyev", "day": 31, "month": 8, "year": 1992, "username": "kenekegood"},
    {"name": "Gulfiya Usserbayeva", "day": 10, "month": 5, "year": 2001, "username": "userbaevaa"},
    {"name": "Akbota Rakym", "day": 29, "month": 3, "year": 1991, "username": "akbota_tur"},
    {"name": "Adilet Ormanov", "day": 15, "month": 2, "year": 1997, "username": "Adil0667"},
    {"name": "Diar Begisbayev", "day": 11, "month": 3, "year": 2004, "username": "diarbegisbayev"},
    {"name": "Aisulu Nurlankyzy", "day": 27, "month": 3, "year": 1995, "username": "asl273"},
    {"name": "Bibigul Abdyraimova", "day": 27, "month": 11, "year": 1996, "username": "abdyraimova"},
    {"name": "Amina Nuradinova", "day": 26, "month": 1, "year": 1998, "username": None},
    {"name": "Daniyar Amantayev", "day": 23, "month": 4, "year": 2001, "username": "jp_doner"},
    {"name": "Bauyrzhan Azimbayev", "day": 15, "month": 3, "year": 1991, "username": "Azimbayev_B"},
    {"name": "Diyar Mukhidenov", "day": 7, "month": 5, "year": 2002, "username": "larga_espera"},
    {"name": "Kamila Zhakupova", "day": 12, "month": 3, "year": 2000, "username": "kmlzh"},
    {"name": "Mirlan Utebayev", "day": 14, "month": 8, "year": 2002, "username": "SadSkyYyy"},
    {"name": "Nurlybek Taubakabyl", "day": 21, "month": 8, "year": 2003, "username": "nurlbk"},
    {"name": "Diana Kazbekova", "day": 18, "month": 3, "year": 1997, "username": "diad_k"},
    {"name": "Akzharkyn Zholmyrza", "day": 29, "month": 3, "year": 1993, "username": "AkzharkynBakytbek"},
    {"name": "Imran Khaider", "day": 12, "month": 4, "year": 2003, "username": "SKGael"},
    {"name": "Aizere Tleubay", "day": 2, "month": 11, "year": 2001, "username": "aizeretleubay"},
    {"name": "Dana Nurgazina", "day": 16, "month": 9, "year": 1996, "username": "DanaNurgazina"},
    {"name": "Bakgeldi Alkhabay", "day": 9, "month": 4, "year": 2002, "username": "bakgeldi"},
    {"name": "Nurbay Kairbek", "day": 15, "month": 9, "year": 2002, "username": "nurrrrrba"},
    {"name": "Aidana Aidynkyzy", "day": 11, "month": 12, "year": 1999, "username": "aidvnaa"},
    {"name": "Samat Tankeyev", "day": 9, "month": 8, "year": 2000, "username": "Steep09"},
    {"name": "Bekdaulet Shapigullin", "day": 17, "month": 2, "year": 2001, "username": "Hardcoderr"},
    {"name": "Xeniya Traxel", "day": 8, "month": 6, "year": 2001, "username": "traxelx"},
    {"name": "Yerassyl Bekenov", "day": 30, "month": 5, "year": 2003, "username": "elienbb"},
    {"name": "Alexey Fedenko", "day": 3, "month": 6, "year": 2003, "username": "alllllexei"},
    {"name": "Daniil Alexandrov", "day": 16, "month": 1, "year": 2003, "username": "Danny_Lisander"},
    {"name": "Abdurakhim Bakytzhan", "day": 28, "month": 11, "year": 2003, "username": "abaCoding"},
    {"name": "Rash Yestebek", "day": 5, "month": 4, "year": 2003, "username": "rash_estebek"},
    {"name": "Aruzhan Mektepbayeva", "day": 14, "month": 7, "year": 2003, "username": "xscherryy"},
    {"name": "Assanali Ospan", "day": 28, "month": 8, "year": 2004, "username": "Asanaliiiiiiiiiiiiiiiiiiiiiiiiii"},
    {"name": "Zhaniya Rakhymbayeva", "day": 9, "month": 2, "year": 2002, "username": "zhaniya_r"},
    {"name": "Tolkyn Tuleutayeva", "day": 12, "month": 9, "year": 2004, "username": "ups_idedown"},
    {"name": "Pavel Tsoy", "day": 27, "month": 1, "year": 2002, "username": "pavelious"},
    {"name": "Miras Kabykenov", "day": 4, "month": 6, "year": 2004, "username": "marmeladpr3"},
    {"name": "Daniyar Kassymov", "day": 4, "month": 7, "year": 2004, "username": "Toxomy"},
]
